baseURL = "https://Balerion-RS.github.io/blocks-teste/"
Title = "BLOCKS"

[params]
themeColor = "ufrj"
description = "The Dwarf Galaxies Group at the Valongo Observatory, Federal University of Rio de Janeiro."
copyright = ""
sidebar_image = "/blocks-teste/images/b.jpeg"


[markup]
  [markup.goldmark.renderer]
    unsafe = true
[menu]

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 20

  [[menu.main]]
    identifier = "publications"
    name = "Publications & Data"
    url = "/publications/"
    weight = 30

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 40